
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOB0-GGg","is_bot":false,"login":"JLowe32","name":""},"headRefName":"Jaren-Jokes-Controller","number":26,"title":"Added Joke Controller and Tests ","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-4/pull/26"},{"author":{"id":"U_kgDOB0-GGg","is_bot":false,"login":"JLowe32","name":""},"headRefName":"Jaren-Jokes","number":25,"title":"Added Joke Service and Tests ","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-4/pull/25"},{"author":{"id":"U_kgDOBdLvhw","is_bot":false,"login":"andersonlee3","name":""},"headRefName":"Anderson-Tides-Controller","number":24,"title":"Tides controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-4/pull/24"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-ZipCode-Controller","number":23,"title":"Added ZipCode Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-4/pull/23"},{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-University-Controller","number":22,"title":"Add University Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-4/pull/22"}]
