
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-HomeController2","number":30,"title":"Customized home controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-4/pull/30"},{"author":{"id":"MDQ6VXNlcjMyNDAyOTk3","is_bot":false,"login":"andrew344c","name":"Andrew"},"headRefName":"Andrew-READMEFixes","number":29,"title":"Adjust links in README.md","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-4/pull/29"}]
